config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:show, :new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :comments, through: :tasks, dependent: :destroy

  def author_name
    user.display_name
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  def author_name
    user.display_name
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.svg'
    end
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :eyecatch
  validates :title, presence: true
  validates :content, presence: true
  validates :date, presence: true

  belongs_to :user
  belongs_to :board
  has_many :comments

  def author_name
    user.display_name
  end

  def comment_count
    comments.count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def display_name
    self.email.split('@')[0]
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.svg'
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
    @comment = @board.comments
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path,notice: '保存できたよ'
    else
      flash.now[:error] = '保存できませんでした'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
	end

  def update
    @board = current_user.boards.find(params[:id])
		if @board.update(board_params)
			redirect_to root_path,
			notice: '更新できました。'
		else
			flash.now[:error] = '更新できませんでした。'
			render :edit
		end
	end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
      redirect_to root_path,
			notice: '削除できました。'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:task_id])
    @comment = @task.comments.build
  end

  def create
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:task_id])
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to board_task_path(@board, @task),notice: 'タスクを保存できました'
    else
      flash.now[:error] = '保存できませんでした。'
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.build_profile
  end

  def update
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '画像更新しました。'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:avatar)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Board.find(params[:board_id]).tasks.build
  end

  def show
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    @comment = @task.comments
  end

  def create
    @task = Board.find(params[:board_id]).tasks.build(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to board_path(Board.find(params[:board_id])),notice: 'タスクを保存できました'
    else
      flash.now[:error] = '保存できませんでした。'
      render :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
	end

  def update
    @board = Board.find(params[:board_id])
    @task = current_user.tasks.find(params[:id])
		if @task.update(task_params)
			redirect_to board_path(@board),
			notice: '更新できました。'
		else
			flash.now[:error] = '更新できませんでした。'
			render :edit
		end
	end

  def destroy
    @board = Board.find(params[:board_id])
    @task = current_user.tasks.find(params[:id])
    if @task.destroy!
      redirect_to board_path(@board),
			notice: '削除できました。'
    else
      flash.now[:error] = '削除できませんでした。'
      render :show
		end
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :date, :eyecatch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: board_path(@board), method: 'put', local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'text'
    %div
      = f.submit '保存',  class: 'submit-btn'

app/views/boards/index.html.haml
.container
  %h1.sectionTitle All Boards
  - @boards.each do |board|
    .board
      .board__menu
        - if user_signed_in? && current_user.has_written?(board)
          .board_detail_actions
            .dropdown
              = image_tag 'actions.svg', class: 'dropbtn'
              .dropdown-content.mini
                = link_to '編集する', edit_board_path(board.id)
                = link_to '削除する', board_path(board.id), data: { method: 'delete', confirm: '本当に削除してよい？'}
      .board__body
        = link_to board_path(id: board.id) do
          .board__title= board.title
          .board__content= board.content
          .avatarIcon= image_tag board.user.avatar_image
  .newBoard
    = link_to '+ Add new board', new_board_path, class: "newBoard__link"

app/views/boards/memo.html.haml
.container
  %h1.sectionTitle All Boards
  - @boards.each do |board|
    = link_to board_path(id: board.id) do
      .board
        .board__head
          .board__title= board.title
          - if user_signed_in? && current_user.has_written?(board)
            .dropdown
              = image_tag 'actions.svg', class: 'board__dropbtn'
              .board__dropdown-content.mini
                = link_to '編集する', edit_board_path(board.id)
                = link_to '削除する', board_path(board.id), data: { method: 'delete', confirm: '本当に削除してよい？'}
        .board__content= board.content
        - if board.user.present?
          %p=board.author_name

  = link_to '+ Add new board', new_board_path

-# :javascript

-#   function btnClick(){
-#     document.getElementById('test').classList.toggle('active');;
-#   }

app/views/boards/new.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: boards_path, method: 'post', local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'text'
    %div
      = f.submit '保存',  class: 'submit-btn'

app/views/boards/show.html.haml
.container
  %h1.sectionTitle=@board.title
  - @tasks.each do |task|
    .task
      = link_to board_task_path(@board.id, task.id) do
        -if task.eyecatch.attached?
          .task__eyecatch= image_tag task.eyecatch
        .task__title= task.title
      - if task.user.present?
        .avatarIcon=image_tag task.user.avatar_image
      .task__commentInfo
        .task__commentUsers
          - @comment.each do |comment|
            .comments__comment
              .comments__icon.avatarIcon=image_tag comment.user.avatar_image
        .task__commentCount= task.comment_count

  .newTask
    = link_to '+ Add new Task', new_board_task_path(@board)

app/views/comments/create.html.haml
createの画面

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message
  .title New Comment
  = form_with(model: @comment, url: board_task_comments_path(@board, @task), local: true) do |f|
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'text'
    %div
      = f.submit '保存',  class: 'submit-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %header.header
      %h1.header__logo Boards
      %div.header__user
        - if user_signed_in?
          .profile__aicon
            .board_detail_actions
              .dropdown
                = image_tag current_user.avatar_image, class: 'dropbtn'
                .dropdown-content.mini.dropdown-content.mini__profile
                  = link_to 'アイコン変更',profile_path
                  = link_to 'ログアウト',destroy_user_session_path, data: {method: 'delete'}
        - else
          = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{class: key}= value
    = yield

app/views/profiles/edit.html.haml
.container

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.profile
  プロフィール画像
  .profile__aicon
    = image_tag current_user.avatar_image

  = link_to '画像変更',edit_profile_path

app/views/tasks/edit.html.haml
.container
  -# %ul
  -#   - @board.errors.full_messages.each do |message|
  -#     %li= message
  = form_with(model: @task, url: board_task_path(@board, @task), local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'text'
    %div
      = f.label :date, '期限'
    %div
      = f.text_area :date, class: 'text'
    %div
      = f.submit '保存',  class: 'submit-btn'

app/views/tasks/new.html.haml
.container
  -# %ul
  -#   - @board.errors.full_messages.each do |message|
  -#     %li= message
  = form_with(model: @task, url: board_tasks_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'text'
    %div
      = f.label :date, '期限'
    %div
      = f.text_area :date, class: 'text'
    %div
      = f.submit '保存',  class: 'submit-btn'

app/views/tasks/show.html.haml
.container
  - if user_signed_in? && current_user.tasks.exists?(id: @task.id)
    .dropdown.task__menu
      = image_tag 'actions.svg', class: 'board__dropbtn'
      .dropdown-content.mini
        = link_to '編集する', edit_board_task_path(@board, @task)
        = link_to '削除する', board_task_path(@board, @task), data: { method: 'delete', confirm: '本当に削除してよい？'}
  %h1.sectionTitle= @task.title
  -if @task.eyecatch.attached?
    .task__eyecatch= image_tag @task.eyecatch
  .task
    .task__content= @task.content

  .comments
  %h2.comments__title Comment
  - @comment.each do |comment|
    .comments__comment
      .comments__icon.avatarIcon=image_tag comment.user.avatar_image
      %p.comments__text= comment.content

  .newComment
    = link_to '+ Add new Comment', new_board_task_comment_path(@board, @task)